kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bluemedora-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bluemedora-monitoring
subjects:
- kind: ServiceAccount
  name: bluemedora-monitoring
  namespace: kube-system
