kind: RoleBinding
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bluemedora-monitoring
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bluemedora-monitoring-role
subjects:
- kind: ServiceAccount
  name: bluemedora-monitoring
  namespace: kube-system
